pipelines:
  default:
    - parallel:
        - step:
            name: Test latest Node.js version
            image: node:latest
            caches:
              - node
            script:
              - echo -e "${NPMRC_JFROG_ARTIFACTORY_1}\n${NPMRC_JFROG_ARTIFACTORY_2}\n${NPMRC_JFROG_ARTIFACTORY_3}" > .npmrc
              - npm ci --unsafe-perm
              - npm test
        - step:
            name: Test LTS 14 Node.js version
            image: node:14
            caches:
              - node
            script:
              - echo -e "${NPMRC_JFROG_ARTIFACTORY_1}\n${NPMRC_JFROG_ARTIFACTORY_2}\n${NPMRC_JFROG_ARTIFACTORY_3}" > .npmrc
              - npm ci --unsafe-perm
              - npm test
        - step:
            name: Test LTS 12 Node.js version
            image: node:12
            caches:
              - node
            script:
              - echo -e "${NPMRC_JFROG_ARTIFACTORY_1}\n${NPMRC_JFROG_ARTIFACTORY_2}\n${NPMRC_JFROG_ARTIFACTORY_3}" > .npmrc
              - npm ci --unsafe-perm
              - npm test
