name: Workflow - Build and Test.

on:
  push:
    branches:
      - release/**
      - develop

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPMRC_JFROG_ARTIFACTORY_TOKEN }}
  NODE_REGISTRY_URL: ${{ secrets.NPMRC_JFROG_ARTIFACTORY_URL }}
  NODE_SCOPE: ${{ secrets.NPMRC_JFROG_ARTIFACTORY_NAMESPACE }}

jobs:
  call_workflow_setup:
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/setup.yml@main
    with:
      branch-ref: ${{ github.head_ref }}
      NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
      NODE_REGISTRY_URL: ${{ env.NODE_REGISTRY_URL }}
      NODE_SCOPE: ${{ env.NODE_SCOPE }}

  call_workflow_build:
    needs: [ call_workflow_setup ]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/build.yml@main
  call_workflow_test:
    needs: [ call_workflow_build ]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/test.yml@main
    with:
      NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
      NODE_REGISTRY_URL: ${{ env.NODE_REGISTRY_URL }}
      NODE_SCOPE: ${{ env.NODE_SCOPE }}
