name: Workflow - Build and Test

on:
  push:
    branches:
      - release/**
      - develop
      - feature/**

jobs:
  call_workflow_setup:
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/setup.yml@main
#    with:
#      node-version: >-
#        ["16", "14"]
#      os: >-
#        ["ubuntu-latest", "windows-latest"]
  call_workflow_build:
    needs: [call_workflow_setup]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/build.yml@main
  call_workflow_test:
    needs: [call_workflow_build]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/test.yml@main
