name: Workflow - Publish.

on:
  push:
    branches:
      - production

env:
  NPM_REGISTRY: private

jobs:
  call_workflow_setup:
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/setup.yml@main
    with:
      branch-ref: ${{ github.head_ref }}
      npm-registry: $NPM_REGISTRY
    secrets: inherit
  call_workflow_build:
    needs: [ call_workflow_setup ]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/build.yml@main
  call_workflow_publish:
    needs: [ call_workflow_build ]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/publish.yml@main
    with:
      npm-registry: $NPM_REGISTRY
    secrets: inherit
