name: Publish to registry and git tag

on:
  push:
    branches:
      - production

jobs:
  call_workflow_setup:
    name: Setup environment
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/setup.yml@main
    with:
      branch-ref: ${{ github.head_ref }}
      jfrog-artifactory: true
    secrets:
#      GLOBAL_ACCESS_TOKEN: ${{ secrets.GLOBAL_ACCESS_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
      scope: ${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_SCOPE }}
      registry-url: ${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_REGISTRY }}
      auth-token: ${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_AUTH }}
  call_workflow_build:
    name: Build project
    needs: [ call_workflow_setup ]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/build.yml@main
  call_workflow_publish:
    name: Publish packages
    needs: [ call_workflow_build ]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/publish.yml@main
