name: Run tests

on:
  push:
    branches:
      - release/**
      - develop

jobs:
  call_workflow_setup:
    name: Setup environment
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/setup.yml@main
    with:
      branch-ref: ${{ github.head_ref }}
      jfrog-artifactory: true
    secrets:
      scope: ${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_SCOPE }}
      registry-url: ${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_REGISTRY }}
      auth-token: ${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_AUTH }}
  call_workflow_build:
    name: Build project
    needs: [ call_workflow_setup ]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/build.yml@main
  call_workflow_test:
    name: Run tests
    needs: [ call_workflow_build ]
    uses: absolunet/github-node-manager-reusable-workflows/.github/workflows/test.yml@main
